/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.externalrepoproject.actordb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * CustomerList generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`customer_list`")
@IdClass(CustomerListId.class)
public class CustomerList implements Serializable {

    private Short id = 0;
    private String name;
    private String address;
    private String zipCode;
    private String phone;
    private String city;
    private String country;
    private String notes;
    private Short sid;

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 5)
    public Short getId() {
        return this.id;
    }

    public void setId(Short id) {
        this.id = id;
    }

    @Id
    @Column(name = "`name`", nullable = true, length = 91)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Id
    @Column(name = "`address`", nullable = false, length = 50)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Id
    @Column(name = "`zip code`", nullable = true, length = 10)
    public String getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    @Id
    @Column(name = "`phone`", nullable = false, length = 20)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Id
    @Column(name = "`city`", nullable = false, length = 50)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Id
    @Column(name = "`country`", nullable = false, length = 50)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Id
    @Column(name = "`notes`", nullable = false, length = 6)
    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Id
    @Column(name = "`SID`", nullable = false, scale = 0, precision = 3)
    public Short getSid() {
        return this.sid;
    }

    public void setSid(Short sid) {
        this.sid = sid;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CustomerList)) return false;
        final CustomerList customerList = (CustomerList) o;
        return Objects.equals(getId(), customerList.getId()) &&
                Objects.equals(getName(), customerList.getName()) &&
                Objects.equals(getAddress(), customerList.getAddress()) &&
                Objects.equals(getZipCode(), customerList.getZipCode()) &&
                Objects.equals(getPhone(), customerList.getPhone()) &&
                Objects.equals(getCity(), customerList.getCity()) &&
                Objects.equals(getCountry(), customerList.getCountry()) &&
                Objects.equals(getNotes(), customerList.getNotes()) &&
                Objects.equals(getSid(), customerList.getSid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName(),
                getAddress(),
                getZipCode(),
                getPhone(),
                getCity(),
                getCountry(),
                getNotes(),
                getSid());
    }
}