/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.externalrepoproject.actordb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class FilmActorId implements Serializable {

    private Short actorId;
    private Short filmId;

    public Short getActorId() {
        return this.actorId;
    }

    public void setActorId(Short actorId) {
        this.actorId = actorId;
    }

    public Short getFilmId() {
        return this.filmId;
    }

    public void setFilmId(Short filmId) {
        this.filmId = filmId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof FilmActor)) return false;
        final FilmActor filmActor = (FilmActor) o;
        return Objects.equals(getActorId(), filmActor.getActorId()) &&
                Objects.equals(getFilmId(), filmActor.getFilmId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getActorId(),
                getFilmId());
    }
}