/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.externalrepoproject.actordb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * SalesByStore generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`sales_by_store`")
@IdClass(SalesByStoreId.class)
public class SalesByStore implements Serializable {

    private String store;
    private String manager;
    private BigDecimal totalSales;

    @Id
    @Column(name = "`store`", nullable = true, length = 101)
    public String getStore() {
        return this.store;
    }

    public void setStore(String store) {
        this.store = store;
    }

    @Id
    @Column(name = "`manager`", nullable = true, length = 91)
    public String getManager() {
        return this.manager;
    }

    public void setManager(String manager) {
        this.manager = manager;
    }

    @Id
    @Column(name = "`total_sales`", nullable = true, scale = 2, precision = 27)
    public BigDecimal getTotalSales() {
        return this.totalSales;
    }

    public void setTotalSales(BigDecimal totalSales) {
        this.totalSales = totalSales;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SalesByStore)) return false;
        final SalesByStore salesByStore = (SalesByStore) o;
        return Objects.equals(getStore(), salesByStore.getStore()) &&
                Objects.equals(getManager(), salesByStore.getManager()) &&
                Objects.equals(getTotalSales(), salesByStore.getTotalSales());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStore(),
                getManager(),
                getTotalSales());
    }
}