/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.externalrepoproject.actordb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class StaffListId implements Serializable {

    private Short id;
    private String name;
    private String address;
    private String zipCode;
    private String phone;
    private String city;
    private String country;
    private Short sid;

    public Short getId() {
        return this.id;
    }

    public void setId(Short id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Short getSid() {
        return this.sid;
    }

    public void setSid(Short sid) {
        this.sid = sid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof StaffList)) return false;
        final StaffList staffList = (StaffList) o;
        return Objects.equals(getId(), staffList.getId()) &&
                Objects.equals(getName(), staffList.getName()) &&
                Objects.equals(getAddress(), staffList.getAddress()) &&
                Objects.equals(getZipCode(), staffList.getZipCode()) &&
                Objects.equals(getPhone(), staffList.getPhone()) &&
                Objects.equals(getCity(), staffList.getCity()) &&
                Objects.equals(getCountry(), staffList.getCountry()) &&
                Objects.equals(getSid(), staffList.getSid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName(),
                getAddress(),
                getZipCode(),
                getPhone(),
                getCity(),
                getCountry(),
                getSid());
    }
}