/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.externalrepoproject.cascadedb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Many2oneCompositeC generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`MANY2ONE_COMPOSITE_C`")
public class Many2oneCompositeC implements Serializable {

    private Integer childId;
    private String childStringId;
    private String childColumn1;
    private String childColumn2;
    private One2manyCompositeP one2manyCompositeP;

    @Id
    @Column(name = "`CHILD_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getChildId() {
        return this.childId;
    }

    public void setChildId(Integer childId) {
        this.childId = childId;
    }

    @Column(name = "`CHILD_STRING_ID`", nullable = true, length = 255)
    public String getChildStringId() {
        return this.childStringId;
    }

    public void setChildStringId(String childStringId) {
        this.childStringId = childStringId;
    }

    @Column(name = "`CHILD_COLUMN1`", nullable = true, length = 255)
    public String getChildColumn1() {
        return this.childColumn1;
    }

    public void setChildColumn1(String childColumn1) {
        this.childColumn1 = childColumn1;
    }

    @Column(name = "`CHILD_COLUMN2`", nullable = true, length = 255)
    public String getChildColumn2() {
        return this.childColumn2;
    }

    public void setChildColumn2(String childColumn2) {
        this.childColumn2 = childColumn2;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumns(value = {
            @JoinColumn(name = "`CHILD_ID`", referencedColumnName = "`PARENT_INT_ID`", insertable = false, updatable = false),
            @JoinColumn(name = "`CHILD_STRING_ID`", referencedColumnName = "`PARENT_STRING_ID`", insertable = false, updatable = false)},
        foreignKey = @ForeignKey(name = "`FK_MANY2ONE_COMPOSITE_C_B8bsx`"))
    @Fetch(FetchMode.JOIN)
    public One2manyCompositeP getOne2manyCompositeP() {
        return this.one2manyCompositeP;
    }

    public void setOne2manyCompositeP(One2manyCompositeP one2manyCompositeP) {
        if(one2manyCompositeP != null) {
            this.childId = one2manyCompositeP.getParentIntId();
            this.childStringId = one2manyCompositeP.getParentStringId();
        }

        this.one2manyCompositeP = one2manyCompositeP;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Many2oneCompositeC)) return false;
        final Many2oneCompositeC many2oneCompositeC = (Many2oneCompositeC) o;
        return Objects.equals(getChildId(), many2oneCompositeC.getChildId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getChildId());
    }
}