/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.externalrepoproject.cascadedb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class One2oneCompUniquePId implements Serializable {

    private String parentStringId;
    private Integer parentIntId;

    public String getParentStringId() {
        return this.parentStringId;
    }

    public void setParentStringId(String parentStringId) {
        this.parentStringId = parentStringId;
    }

    public Integer getParentIntId() {
        return this.parentIntId;
    }

    public void setParentIntId(Integer parentIntId) {
        this.parentIntId = parentIntId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof One2oneCompUniqueP)) return false;
        final One2oneCompUniqueP one2oneCompUniqueP = (One2oneCompUniqueP) o;
        return Objects.equals(getParentStringId(), one2oneCompUniqueP.getParentStringId()) &&
                Objects.equals(getParentIntId(), one2oneCompUniqueP.getParentIntId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getParentStringId(),
                getParentIntId());
    }
}