/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.externalrepoproject.cascadedb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.externalrepoproject.cascadedb.Many2oneCompositeC;
import com.externalrepoproject.cascadedb.One2manyCompositeP;
import com.externalrepoproject.cascadedb.One2manyCompositePId;

/**
 * Service object for domain model class {@link One2manyCompositeP}.
 */
public interface One2manyCompositePService {

    /**
     * Creates a new One2manyCompositeP. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on One2manyCompositeP if any.
     *
     * @param one2manyCompositeP Details of the One2manyCompositeP to be created; value cannot be null.
     * @return The newly created One2manyCompositeP.
     */
    One2manyCompositeP create(@Valid One2manyCompositeP one2manyCompositeP);


	/**
     * Returns One2manyCompositeP by given id if exists.
     *
     * @param one2manycompositepId The id of the One2manyCompositeP to get; value cannot be null.
     * @return One2manyCompositeP associated with the given one2manycompositepId.
	 * @throws EntityNotFoundException If no One2manyCompositeP is found.
     */
    One2manyCompositeP getById(One2manyCompositePId one2manycompositepId);

    /**
     * Find and return the One2manyCompositeP by given id if exists, returns null otherwise.
     *
     * @param one2manycompositepId The id of the One2manyCompositeP to get; value cannot be null.
     * @return One2manyCompositeP associated with the given one2manycompositepId.
     */
    One2manyCompositeP findById(One2manyCompositePId one2manycompositepId);

	/**
     * Find and return the list of One2manyCompositePs by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param one2manycompositepIds The id's of the One2manyCompositeP to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return One2manyCompositePs associated with the given one2manycompositepIds.
     */
    List<One2manyCompositeP> findByMultipleIds(List<One2manyCompositePId> one2manycompositepIds, boolean orderedReturn);


    /**
     * Updates the details of an existing One2manyCompositeP. It replaces all fields of the existing One2manyCompositeP with the given one2manyCompositeP.
     *
     * This method overrides the input field values using Server side or database managed properties defined on One2manyCompositeP if any.
     *
     * @param one2manyCompositeP The details of the One2manyCompositeP to be updated; value cannot be null.
     * @return The updated One2manyCompositeP.
     * @throws EntityNotFoundException if no One2manyCompositeP is found with given input.
     */
    One2manyCompositeP update(@Valid One2manyCompositeP one2manyCompositeP);

    /**
     * Deletes an existing One2manyCompositeP with the given id.
     *
     * @param one2manycompositepId The id of the One2manyCompositeP to be deleted; value cannot be null.
     * @return The deleted One2manyCompositeP.
     * @throws EntityNotFoundException if no One2manyCompositeP found with the given id.
     */
    One2manyCompositeP delete(One2manyCompositePId one2manycompositepId);

    /**
     * Deletes an existing One2manyCompositeP with the given object.
     *
     * @param one2manyCompositeP The instance of the One2manyCompositeP to be deleted; value cannot be null.
     */
    void delete(One2manyCompositeP one2manyCompositeP);

    /**
     * Find all One2manyCompositePs matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching One2manyCompositePs.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<One2manyCompositeP> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all One2manyCompositePs matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching One2manyCompositePs.
     *
     * @see Pageable
     * @see Page
     */
    Page<One2manyCompositeP> findAll(String query, Pageable pageable);

    /**
     * Exports all One2manyCompositePs matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all One2manyCompositePs matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the One2manyCompositePs in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the One2manyCompositeP.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated many2oneCompositeCs for given One2manyCompositeP id.
     *
     * @param parentStringId value of parentStringId; value cannot be null
     * @param parentIntId value of parentIntId; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Many2oneCompositeC instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Many2oneCompositeC> findAssociatedMany2oneCompositeCs(String parentStringId, Integer parentIntId, Pageable pageable);

}