/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.externalrepoproject.cascadedb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.externalrepoproject.cascadedb.One2oneUcP;

/**
 * Service object for domain model class {@link One2oneUcP}.
 */
public interface One2oneUcPService {

    /**
     * Creates a new One2oneUcP. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on One2oneUcP if any.
     *
     * @param one2oneUcP Details of the One2oneUcP to be created; value cannot be null.
     * @return The newly created One2oneUcP.
     */
    One2oneUcP create(@Valid One2oneUcP one2oneUcP);


	/**
     * Returns One2oneUcP by given id if exists.
     *
     * @param one2oneucpId The id of the One2oneUcP to get; value cannot be null.
     * @return One2oneUcP associated with the given one2oneucpId.
	 * @throws EntityNotFoundException If no One2oneUcP is found.
     */
    One2oneUcP getById(Integer one2oneucpId);

    /**
     * Find and return the One2oneUcP by given id if exists, returns null otherwise.
     *
     * @param one2oneucpId The id of the One2oneUcP to get; value cannot be null.
     * @return One2oneUcP associated with the given one2oneucpId.
     */
    One2oneUcP findById(Integer one2oneucpId);

	/**
     * Find and return the list of One2oneUcPs by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param one2oneucpIds The id's of the One2oneUcP to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return One2oneUcPs associated with the given one2oneucpIds.
     */
    List<One2oneUcP> findByMultipleIds(List<Integer> one2oneucpIds, boolean orderedReturn);


    /**
     * Updates the details of an existing One2oneUcP. It replaces all fields of the existing One2oneUcP with the given one2oneUcP.
     *
     * This method overrides the input field values using Server side or database managed properties defined on One2oneUcP if any.
     *
     * @param one2oneUcP The details of the One2oneUcP to be updated; value cannot be null.
     * @return The updated One2oneUcP.
     * @throws EntityNotFoundException if no One2oneUcP is found with given input.
     */
    One2oneUcP update(@Valid One2oneUcP one2oneUcP);

    /**
     * Deletes an existing One2oneUcP with the given id.
     *
     * @param one2oneucpId The id of the One2oneUcP to be deleted; value cannot be null.
     * @return The deleted One2oneUcP.
     * @throws EntityNotFoundException if no One2oneUcP found with the given id.
     */
    One2oneUcP delete(Integer one2oneucpId);

    /**
     * Deletes an existing One2oneUcP with the given object.
     *
     * @param one2oneUcP The instance of the One2oneUcP to be deleted; value cannot be null.
     */
    void delete(One2oneUcP one2oneUcP);

    /**
     * Find all One2oneUcPs matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching One2oneUcPs.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<One2oneUcP> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all One2oneUcPs matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching One2oneUcPs.
     *
     * @see Pageable
     * @see Page
     */
    Page<One2oneUcP> findAll(String query, Pageable pageable);

    /**
     * Exports all One2oneUcPs matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all One2oneUcPs matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the One2oneUcPs in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the One2oneUcP.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}