/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.externalrepoproject.actordb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.externalrepoproject.actordb.FilmList;
import com.externalrepoproject.actordb.FilmListId;

/**
 * Service object for domain model class {@link FilmList}.
 */
public interface FilmListService {

    /**
     * Creates a new FilmList. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on FilmList if any.
     *
     * @param filmList Details of the FilmList to be created; value cannot be null.
     * @return The newly created FilmList.
     */
    FilmList create(@Valid FilmList filmList);


	/**
     * Returns FilmList by given id if exists.
     *
     * @param filmlistId The id of the FilmList to get; value cannot be null.
     * @return FilmList associated with the given filmlistId.
	 * @throws EntityNotFoundException If no FilmList is found.
     */
    FilmList getById(FilmListId filmlistId);

    /**
     * Find and return the FilmList by given id if exists, returns null otherwise.
     *
     * @param filmlistId The id of the FilmList to get; value cannot be null.
     * @return FilmList associated with the given filmlistId.
     */
    FilmList findById(FilmListId filmlistId);

	/**
     * Find and return the list of FilmLists by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param filmlistIds The id's of the FilmList to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return FilmLists associated with the given filmlistIds.
     */
    List<FilmList> findByMultipleIds(List<FilmListId> filmlistIds, boolean orderedReturn);


    /**
     * Updates the details of an existing FilmList. It replaces all fields of the existing FilmList with the given filmList.
     *
     * This method overrides the input field values using Server side or database managed properties defined on FilmList if any.
     *
     * @param filmList The details of the FilmList to be updated; value cannot be null.
     * @return The updated FilmList.
     * @throws EntityNotFoundException if no FilmList is found with given input.
     */
    FilmList update(@Valid FilmList filmList);

    /**
     * Deletes an existing FilmList with the given id.
     *
     * @param filmlistId The id of the FilmList to be deleted; value cannot be null.
     * @return The deleted FilmList.
     * @throws EntityNotFoundException if no FilmList found with the given id.
     */
    FilmList delete(FilmListId filmlistId);

    /**
     * Deletes an existing FilmList with the given object.
     *
     * @param filmList The instance of the FilmList to be deleted; value cannot be null.
     */
    void delete(FilmList filmList);

    /**
     * Find all FilmLists matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching FilmLists.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<FilmList> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all FilmLists matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching FilmLists.
     *
     * @see Pageable
     * @see Page
     */
    Page<FilmList> findAll(String query, Pageable pageable);

    /**
     * Exports all FilmLists matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all FilmLists matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the FilmLists in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the FilmList.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}