/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.externalrepoproject.actordb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.externalrepoproject.actordb.SalesByStore;
import com.externalrepoproject.actordb.SalesByStoreId;

/**
 * Service object for domain model class {@link SalesByStore}.
 */
public interface SalesByStoreService {

    /**
     * Creates a new SalesByStore. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on SalesByStore if any.
     *
     * @param salesByStore Details of the SalesByStore to be created; value cannot be null.
     * @return The newly created SalesByStore.
     */
    SalesByStore create(@Valid SalesByStore salesByStore);


	/**
     * Returns SalesByStore by given id if exists.
     *
     * @param salesbystoreId The id of the SalesByStore to get; value cannot be null.
     * @return SalesByStore associated with the given salesbystoreId.
	 * @throws EntityNotFoundException If no SalesByStore is found.
     */
    SalesByStore getById(SalesByStoreId salesbystoreId);

    /**
     * Find and return the SalesByStore by given id if exists, returns null otherwise.
     *
     * @param salesbystoreId The id of the SalesByStore to get; value cannot be null.
     * @return SalesByStore associated with the given salesbystoreId.
     */
    SalesByStore findById(SalesByStoreId salesbystoreId);

	/**
     * Find and return the list of SalesByStores by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param salesbystoreIds The id's of the SalesByStore to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return SalesByStores associated with the given salesbystoreIds.
     */
    List<SalesByStore> findByMultipleIds(List<SalesByStoreId> salesbystoreIds, boolean orderedReturn);


    /**
     * Updates the details of an existing SalesByStore. It replaces all fields of the existing SalesByStore with the given salesByStore.
     *
     * This method overrides the input field values using Server side or database managed properties defined on SalesByStore if any.
     *
     * @param salesByStore The details of the SalesByStore to be updated; value cannot be null.
     * @return The updated SalesByStore.
     * @throws EntityNotFoundException if no SalesByStore is found with given input.
     */
    SalesByStore update(@Valid SalesByStore salesByStore);

    /**
     * Deletes an existing SalesByStore with the given id.
     *
     * @param salesbystoreId The id of the SalesByStore to be deleted; value cannot be null.
     * @return The deleted SalesByStore.
     * @throws EntityNotFoundException if no SalesByStore found with the given id.
     */
    SalesByStore delete(SalesByStoreId salesbystoreId);

    /**
     * Deletes an existing SalesByStore with the given object.
     *
     * @param salesByStore The instance of the SalesByStore to be deleted; value cannot be null.
     */
    void delete(SalesByStore salesByStore);

    /**
     * Find all SalesByStores matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching SalesByStores.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<SalesByStore> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all SalesByStores matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching SalesByStores.
     *
     * @see Pageable
     * @see Page
     */
    Page<SalesByStore> findAll(String query, Pageable pageable);

    /**
     * Exports all SalesByStores matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all SalesByStores matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the SalesByStores in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the SalesByStore.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}